### PR TITLE
Moment as a peerDependency.

### PR DESCRIPTION
**Pull request by benmosher**

### CODE REVIEW

**Comment by benmosher** [comment]
If moment is not a peer dependency, it can end up installing its own `moment` in its `node_modules`, which is the one it extends, but not the one that is returned by `require('moment')` in the application code.

This affected my builds both in Node and Webpack'd browser builds. Peer dependency fixed it.

Notably: you won't see the problem if `moment` is installed first, as `npm` can notice and not re-install, but this is not guaranteed. Installing `twix`, then `moment` should yield the issue.

**Comment by benmosher** [comment]
FWIW, I think this also resolves #67.

**Comment by icambron** [comment]
Oh, I bet it does. @vdmitriy can you confirm?

**Comment by icambron** [comment]
@benmosher Thanks!

**Comment by icambron** [comment]
Published as 0.6.4

**Comment by vdmitriy** [comment]
Unfortunately no ...

**Pull request merged**
