### PR TITLE
Add floating point parameter to length method.

### PR DESCRIPTION
**Pull request by feload**
Since moment "diff" method is able to receive an optional parameter for including floating point, I thought it was a good idea to add it to twix "length" method.

### CODE REVIEW

**Comment by icambron** [comment]
This looks good to me. The test failure is a bit mysterious; I'll look into that. One change I need from you though is to remove the minified files from your commit. Thanks!

**Comment by feload** [comment]
Awesome, thanks! Files removed.

**Comment by icambron** [comment]
Looks like you deleted the built files from the repo, not from the commit. I want the files, I just don't want your changes to them.

I also got Travis to give me the error (it was being weird when I first looked at this); it's complaining about the semicolons. You can run `make lint` to test that locally.

**Comment by feload** [comment]
Ok, I think we're good to go now. I'm sorry this is my first time contributing :)

**Comment by icambron** [comment]
No problem! Thanks for the contribution.

**Comment by icambron** [comment]
@feload This is released as part of 1.1.4

**Pull request merged**
