### PR TITLE
Add support for half-open ranges

### PR DESCRIPTION
**Pull request by butterflyhug**
@icambron  I'm opening this as a very minimal PR because I'd like your feedback on the implementation approach.  If you like what you see here, I'll work on updating the docs and adding some simple tests.

I've added support for an "containEndpoints" configuration option when constructing a new Twix range.  There are four valid values for the containEndpoints option:

- `true`:  construct a fully closed range, where the range contains both its start and end moments
- `"end"`:  construct a half open range, where the range contains its end but not its start moment
- `"start"`:  construct a half open range, where the range contains its start but not its end moment
- `false`:  construct a fully open range that contains neither its start nor end moments

This is implemented by twiddling the values of `_trueStart` and `_trueEnd` in Twix's constructor, minimizing the impact on code complexity.  I haven't tested everything comprehensively yet, but based on some informal testing of various API methods, I feel like the resulting behavior matches my expectations quite nicely — formatting functions are generally unaffected, while mathematical functions appear to consistently respect the munged endpoints.

It is worth noting that Twix's set algebra functions (e.g. `Twix.intersection`) will currently always act on the `_trueStart` and `_trueEnd` values to create a mathematically-correct closed range, even if one of the source ranges was a half-open or fully open range.  This might be unintuitive for some formatting-centric use cases.

The default value of containEndpoints is `true`, for backward compatibility with previous versions of Twix.

This PR is largely motivated by our discussion in #44.  Sorry it took me so long to follow up on this!

### CODE REVIEW

**Comment by icambron** [comment]
I like it, and I also like how small it is. Thanks for working on it.

> formatting functions are generally unaffected, while mathematical functions appear to consistently respect the munged endpoints.

This sounds right to me; I don't think it should affect formatting.

> It is worth noting that Twix's set algebra functions (e.g. Twix.intersection) will currently always act on the _trueStart and _trueEnd values to create a mathematically-correct closed range, even if one of the source ranges was a half-open or fully open range. This might be unintuitive for some formatting-centric use cases.

Yeah, that's a bit thorny, since we don't provide any way to turn a closed range into a half-open range. I don't want to add an argument to all of those functions, though. I think perhaps it should just inherit the openness of the first range. I'd suggest stashing `@openness` (or whatever) in the constructor and passing it to the constructors in the algebra methods.

One minor thing I haven't thought about hard enough: I adjusted those functions to do some funny stuff because we didn't have open or half open ranges. See, e.g., #8, which makes `overlaps()` return true for adjacent ranges, even though they're closed. It's tempting to change that to `false` now that there are open ranges for which it should return `true`. But I guess I don't want to break reverse compat, so let's table that.

Final thing is that we should make equality take endpoint inclusion into account. A half-open range between two times is not the same as a fully closed range between those two times. So need to change `equals()`.

So if you make the set functions "inherit" their inclusiveness, change `equals` and add some tests, I'll gladly mere this.

**Comment by butterflyhug** [comment]
Thanks for the awesome feedback!  I think I agree with all your suggestions, so I'll keep working on this over the next few days.

**Comment by icambron** [comment]
You guys are here in Cambridge, right? When you get this done I'll buy you and @benesch a beer.

**Comment by butterflyhug** [comment]
Re: the behavior from #8 in `overlaps`, I feel like the right way to fix that is to strip out the funky logic and just change the default to create half-open ranges instead of fully-closed ranges.  But as you say, that obviously breaks backward compatibility, so it makes sense to consider the tradeoffs of that change separately.

**Comment by butterflyhug** [comment]
Yep!  I'd totally be up for a beer at some point.  :+1:

**Comment by butterflyhug** [comment]
Checkpoint:  I've updated `.equals()` and `.union()`, including tests for `.union()`.  I still need to do similar updates for the other set functions and their tests.  I also still need to evaluate other portions of the API to figure out what else deserves additional tests, and write those tests.

**Comment by icambron** [comment]
:+1:

**Comment by icambron** [comment]
Just checking in on this. I've sort of lost track of this, but IIRC, there's still a few things to do?

**Comment by butterflyhug** [comment]
Yep, thanks for poking me -- this slipped off my radar too.  My recollection is that I just need to finish up support for several of the set operators (`.xor` looked a bit more involved than most of the others).

I just got back from vacation so I'm a bit busier than usual this week, but I'll try to bring this up to date and finish the remaining work by the end of the month or so.

**Comment by butterflyhug** [comment]
I'm closing this PR.  I'm definitely still interested in the idea, but I'm not sure if/when I'll get time to work on it again.  Also, while there's a lot of ideas that could be usefully copied from these commits, I suspect it'd be easier to re-implement instead of trying to directly merge these commits with the current codebase.

**Pull request closed without merging**
